### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by SamCreamer** [djangodeployment/django-deployment-book#12] opened 2019-03-18 14:32 UTC
"If you want don't know what to do"

First section of the web server chapter

**Comment by SamCreamer** [comment] 2019-03-19 12:07
(believe it's supposed to be "If you don't know what to do" or "If you don't know what you want to do")

**Comment by aptiko** [comment] 2019-04-13 16:20
Hi. This is a duplicate of #5, which I just fixed. Thanks anyway for reporting.

BTW, the book is now also available online at https://djangodeployment.readthedocs.io/

**Closed as completed by aptiko** 2019-04-13 16:20 UTC
Labels: duplicate

**Comment by SamCreamer** [comment] 2019-04-13 16:22
Thanks, love the book
